#app
server:
  port: 8080

#spring
spring:
    devtools:
      restart:
        enabled: false
    application:
        name: ADMIN2
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/smurfs?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    cache:
        type: redis
    redis:
      host: 127.0.0.1 #redis服务器地址
      timeout: 10000 #超时时间
      database: 0 #0-15 16个库 默认0
      lettuce:
        pool:
          max-active: 8 #最大连接数
          max-wait: -1 #默认-1 最大连接阻塞等待时间
          max-idle: 8 #最大空闲连接 默认8
          min-idle: 0 #最小空闲连接
      port: 6379
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.baomidou.springboot.entity
  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 30
  client:
    heathcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#ribbon:
#  eureka:
#    enable: true
logging:
  config: classpath:logback.xml
