server:
  port: 9010
spring:
  application:
    name: register #name必须一样，不然高可用会导致unavailable-replicas
eureka:
  instance:
    hostname: register1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://register2:9011/eureka/