#app
server:
  port: 8080
  servlet:
     context-path: /admin2
#spring
spring:
    devtools:
      restart:
        enabled: false
    application:
        name: ADMIN2
#    datasource:
#        name: test
#        url: jdbc:mysql://127.0.0.1:3306/smurfs?useUnicode=true&characterEncoding=utf8
#        username: root
#        password: root
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat,wall,log4j
#        initialSize: 5
#        maxActive: 20
#        maxPoolPreparedStatementPerConnectionSize: 20
#        maxWait: 60000
#        minEvictableIdleTimeMillis: 300000
#        minIdle: 5
#        poolPreparedStatements: true
#        testOnBorrow: false
#        testOnReturn: false
#        testWhileIdle: true
#        timeBetweenEvictionRunsMillis: 60000
#        useGlobalDataSourceStat: true
#        validationQuery: SELECT 1 FROM DUAL
#        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis-plus:
  mapper-locations: classpath:/mapping/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  configuration:
    mapUnderscoreToCamelCase: false

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 30
  client:
    heathcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

logging:
  config: classpath:logback.xml

database:
  name: smurfs

management:
  endpoints:
    web:
     exposure:
       include: health,info,env,metrics,beans
