server:
  port: 8993
  servlet:
    context-path: /auth
spring:
    application:
        name: AUTHSERVICE
    redis:
      host: 127.0.0.1 #redis服务器地址
      timeout: 10000 #超时时间
      database: 0 #0-15 16个库 默认0
      lettuce:
        pool:
          max-active: 8 #最大连接数
          max-wait: -1 #默认-1 最大连接阻塞等待时间
          max-idle: 8 #最大空闲连接 默认8
          min-idle: 0 #最小空闲连接
      port: 6379
eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 30
  client:
    heathcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
jwt:
  expire: 60000
auth:
  user:
      token-header: Authorization
#spring:
#  cloud:
#    config:
#      discovery:
#        serviceId: CONFIGSERVER
#        enabled: true
#  profiles:
#      active: prod
#ribbon:
#  eureka:
#    enable: true