server:
  port: 8999

spring:
    application:
        name: DBSERVICE
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/smurfs?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    cache:
        type: redis
    redis:
      host: 127.0.0.1 #redis服务器地址
      timeout: 10000 #超时时间
      database: 0 #0-15 16个库 默认0
      lettuce:
        pool:
          max-active: 8 #最大连接数
          max-wait: -1 #默认-1 最大连接阻塞等待时间
          max-idle: 8 #最大空闲连接 默认8
          min-idle: 0 #最小空闲连接
      port: 6379
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.iscas.smurfs.core.entity  # 注意：对应实体类的路径
  configuration:
      mapUnderscoreToCamelCase: true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 30
  client:
    heathcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
auth:
  user:
    token-header: Authorization
#ribbon:
#  eureka:
#    enable: true
